export const environment = {
  production: true,
  apiURL: "http://softlandcloudbackendcert.azurewebsites.net/api/",
  urlAdmins: "admin/administradores",
  urlAdminsFilter: "admin/administradores_rol",
  urlApps: "aplicaciones",
  urlClients: "clientes",
  urlClientsFilter: "clientes/admin",
  urlCompanies: "empresas",
  urlCompaniesFilter: "empresas/admin",
  urlInstances: "instancias",
  urlInstancesFilter: "instancias/admin",
  urlLicenses: "licencias",
  urlLicensesFilter: "licencias/admin",
  urlLogin: "admin/login",
  urlModules: "modulos",
  urlPermissions: "tipos_permisos",
  urlProjects: "proyectos",
  urlRoles: "admin/roles",
  urlUsers: "usuarios",
  urlUsersFilter: "usuarios/admin"
};
